spring:
  profiles:
    active: dev
---
server:
  port: 8848
  max-http-header-size: 4048576 #Request header is too large异常解决
spring:
  application:
    name: COMMON-PROVIDER 
  profiles: dev
eureka:
  instance:
    hostname: localhsot
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8849
  max-http-header-size: 4048576 #Request header is too large异常解决
spring:
  application:
    name: COMMON-PROVIDER 
  profiles: test
eureka:
  instance:
    hostname: localhsot
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
