

server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZULL-GATEWAY  #服务的名字
  profiles: dev #开发环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #服务注册的注册中心的地址
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
---
server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZULL-GATEWAY-TEST  #服务的名字
  profiles: test #开发环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #服务注册的注册中心的地址
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: "/aigo"
  ignored-services: "*"
  routes:
    plat.serviceId: plat-service
    plat.path: /plat/**
